Update Connector Master SDK Workflow.yml

diff --git a/.github/workflows/Connector Master SDK Workflow.yml b/.github/workflows/Connector Master SDK Workflow.yml
--- a/.github/workflows/Connector Master SDK Workflow.yml
+++ b/.github/workflows/Connector Master SDK Workflow.yml
@@ -161,40 +161,40 @@ jobs:
         shell: python
         continue-on-error: true
         
-      - name: Get SonarCloud Status
-        id: get-sonarcloud-status
-        run: |
-          sonarCloudProjectStatus=$(curl -s -u "${{ env.SONAR_TOKEN }}:" "https://sonarcloud.io/api/qualitygates/project_status?projectKey=${{ inputs.sonarCloudProjectName }}")
+      # - name: Get SonarCloud Status
+      #   id: get-sonarcloud-status
+      #   run: |
+      #     sonarCloudProjectStatus=$(curl -s -u "${{ env.SONAR_TOKEN }}:" "https://sonarcloud.io/api/qualitygates/project_status?projectKey=${{ inputs.sonarCloudProjectName }}")
 
-          # Check if the response is empty or not valid JSON
-          if [ -z "$sonarCloudProjectStatus" ] || ! echo "$sonarCloudProjectStatus" | jq . > /dev/null 2>&1; then
-            echo "Error: The SONAR_TOKEN is invalid, expired, or the response is empty. Please check: https://sonarcloud.io/account/security and update your token: https://github.com/${{ github.repository }}/settings/secrets/actions" >&2
-            echo "Returned response: $sonarCloudProjectStatus" >&2
-            exit 1
-          fi
+      #     # Check if the response is empty or not valid JSON
+      #     if [ -z "$sonarCloudProjectStatus" ] || ! echo "$sonarCloudProjectStatus" | jq . > /dev/null 2>&1; then
+      #       echo "Error: The SONAR_TOKEN is invalid, expired, or the response is empty. Please check: https://sonarcloud.io/account/security and update your token: https://github.com/${{ github.repository }}/settings/secrets/actions" >&2
+      #       echo "Returned response: $sonarCloudProjectStatus" >&2
+      #       exit 1
+      #     fi
 
-          # Output the JSON response if valid
-          echo "Returned response: $sonarCloudProjectStatus"
-          echo "sonarCloudProjectStatus=$sonarCloudProjectStatus" >> $GITHUB_OUTPUT
-        continue-on-error: false
-        shell: bash
-
-      - name: Trigger Initial Analysis
-        if: fromJson(steps.get-sonarcloud-status.outputs.sonarCloudProjectStatus).projectStatus.status  == 'NONE'
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
-        run: |
-            dotnet sonarscanner begin `
-              /k:"${{ inputs.sonarCloudProjectName }}" `
-              /o:"${{ env.lowerCaseOwner }}" `
-              /d:sonar.token="${{ env.SONAR_TOKEN }}" `
-              /d:sonar.host.url="https://sonarcloud.io" `
-              /d:sonar.cs.opencover.reportsPaths="**/TestResults/**/coverage.opencover.xml" `
-              /d:sonar.cs.vstest.reportsPaths="**/TestResults/**.trx" `
-              /d:sonar.exclusions="**/*.yml,**/*.xml"
-            dotnet build "${{ steps.findSlnFile.outputs.solutionFilePath }}" -p:DefineConstants="DCFv1%3BDBInfo%3BALARM_SQUASHING" --configuration Release -nodeReuse:false
-            dotnet sonarscanner end /d:sonar.token="${{ env.SONAR_TOKEN  }}"
-        continue-on-error: true
+      #     # Output the JSON response if valid
+      #     echo "Returned response: $sonarCloudProjectStatus"
+      #     echo "sonarCloudProjectStatus=$sonarCloudProjectStatus" >> $GITHUB_OUTPUT
+      #   continue-on-error: false
+      #   shell: bash
+        
+      # - name: Trigger Initial Analysis
+      #   if: fromJson(steps.get-sonarcloud-status.outputs.sonarCloudProjectStatus).projectStatus.status  == 'NONE'
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
+      #   run: |
+      #       dotnet sonarscanner begin `
+      #         /k:"${{ inputs.sonarCloudProjectName }}" `
+      #         /o:"${{ env.lowerCaseOwner }}" `
+      #         /d:sonar.token="${{ env.SONAR_TOKEN }}" `
+      #         /d:sonar.host.url="https://sonarcloud.io" `
+      #         /d:sonar.cs.opencover.reportsPaths="**/TestResults/**/coverage.opencover.xml" `
+      #         /d:sonar.cs.vstest.reportsPaths="**/TestResults/**.trx" `
+      #         /d:sonar.exclusions="**/*.yml,**/*.xml"
+      #       dotnet build "${{ steps.findSlnFile.outputs.solutionFilePath }}" -p:DefineConstants="DCFv1%3BDBInfo%3BALARM_SQUASHING" --configuration Release -nodeReuse:false
+      #       dotnet sonarscanner end /d:sonar.token="${{ env.SONAR_TOKEN  }}"
+      #   continue-on-error: true
 
       - name: Start Analysis
         env:
